# Use an official Node.js runtime as the base image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Install Nodemon globally for hot reloading
RUN npm install -g nodemon

# Copy the rest of the application source code to the working directory
COPY . .

# Expose the port your app runs on (if your app runs on port 3000, for example)
EXPOSE 3000

# Start the application using Nodemon for hot reloading
CMD ["nodemon", "index.js"]
